name: bytedesk_kefu
description: the best app chat sdk in china, you can chat with the agent freely at anytime. the agent can chat with the visitor by web/pc/mac/ios/android client.
version: 1.3.1
homepage: https://www.weikefu.net

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  # Localization https://github.com/dart-lang/intl
  intl: ^0.17.0
  # https://pub.dev/packages/meta/install
  meta: ^1.7.0
  # https://pub.dev/packages/equatable
  equatable: ^2.0.3
  # https://pub.dev/packages/flutter_bloc
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  # https://pub.dev/packages/http
  http: ^0.13.4
  http_parser: ^4.0.0
  # 事件通知总线
  # https://pub.dev/packages/event_bus
  event_bus: ^2.0.0
  # https://flutter.dev/docs/cookbook/persistence/sqlite
  # https://pub.dev/packages/sqflite
  sqflite: ^2.0.2+1
  # https://pub.dev/packages/path
  path: ^1.8.0
  # https://pub.dev/packages/permission_handler
  # permission_handler: ^8.2.5
  # https://pub.dev/packages/sp_util
  sp_util: ^2.0.3
  # 图片选择插件
  # https://pub.dev/packages/image_picker
  image_picker: ^0.8.5
  # image_picker在选择视频的时候有bug，选此替代 https://pub.dev/packages/file_picker
  file_picker: ^4.5.1
  # https://pub.dev/packages/protobuf
  protobuf: ^2.0.1
  # 下拉刷新 https://pub.dev/packages/flutter_easyrefresh
  flutter_easyrefresh: ^2.2.1
  # toast https://pub.dev/packages/fluttertoast
  fluttertoast: ^8.0.9
  # https://pub.dev/packages/flutter_easyloading
  flutter_easyloading: ^3.0.3
  # H5-webchat https://pub.dev/packages/webview_flutter
  # webview_flutter: ^3.0.2
  webview_flutter: ^2.0.4
  # https://pub.dev/packages/device_info
  device_info: ^2.0.3
  # 查看大图 https://pub.dev/packages/photo_view
  photo_view: ^0.13.0
  # 图片缓存 https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.2.0
  # 满意度评价 https://pub.dev/packages/flutter_rating_bar
  # flutter_rating_bar: ^4.0.0
  # 手机语言 https://pub.dev/packages/devicelocale
  devicelocale: ^0.5.0
  # https://pub.dev/packages/package_info
  package_info: ^2.0.2
  # 输入框 https://pub.dev/packages/extended_text_field
  # extended_text_field: ^8.0.0
  # https://pub.dev/packages/pull_to_refresh
  pull_to_refresh: ^2.0.0
  # 图片压缩 https://pub.dev/packages/flutter_image_compress
  # flutter_image_compress: ^0.7.0
  # 视频压缩 https://pub.dev/packages/flutter_video_compress/install
  # flutter_video_compress: ^0.3.7+8
  # 振动 https://pub.dev/packages/vibration
  # vibration: ^1.7.3
  # 播放语音
  # https://pub.dev/packages/audioplayers
  # audioplayers: ^0.16.1
  # https://pub.dev/packages/flutter_html
  # https://github.com/Sub6Resources/flutter_html
  # flutter_html: ^3.0.0-alpha.3 # bug：界面不能及时更新
  flutter_html: ^2.2.1
  # https://pub.dev/packages/flutter_cache_manager
  flutter_cache_manager: ^3.3.0
  # 保存图片到相册
  # https://pub.flutter-io.cn/packages/image_gallery_saver
  image_gallery_saver: ^1.7.1
  # https://pub.dev/packages/feedback
  # feedback: ^2.0.0-beta.0
  # feedback: ^1.2.2
  # 替代 dart:html 以便于在APP上运行, mqtt依赖
  # https://pub.dev/packages/universal_html
  universal_html: ^2.0.8
  # flutter_html依赖下列
  # html: ^0.15.0
  # mqtt_client依赖
  typed_data: ^1.3.0
  crypto: ^3.0.2
  # Plugins for parsing css
  csslib: ^0.17.1
  css_colors: ^1.1.1
  # Plugins for rendering the <video> tag.
  video_player: ^2.4.0
  # chewie: ^1.2.2 # 与 flutter_html: ^3.0.0-alpha.3 不兼容
  # chewie:
  #   git:
  #     url: https://github.com/brianegan/chewie.git
  # https://pub.dev/packages/provider
  provider: ^6.0.2
  # https://pub.dev/packages/wakelock
  wakelock: ^0.6.1+2

  # Plugins for rendering the <audio> tag.
  # chewie_audio: ^1.0.0+1
  # Plugins for rendering the <svg> tag.
  # flutter_svg: ^1.0.3
  flutter_svg: ^0.23.0+1

  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.bytedesk.bytedesk_kefu
        pluginClass: BytedeskKefuPlugin
      ios:
        pluginClass: BytedeskKefuPlugin
      linux:
        pluginClass: BytedeskKefuPlugin
      macos:
        pluginClass: BytedeskKefuPlugin
      windows:
        pluginClass: BytedeskKefuPlugin
      web:
        pluginClass: BytedeskKefuWeb
        fileName: bytedesk_kefu_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
